FROM python:3.11-slim

WORKDIR /mlflow

RUN pip install --no-cache-dir mlflow[extras]

RUN mkdir -p /mlflow/mlruns

COPY . .

CMD mlflow server \
  --backend-store-uri sqlite:///mlflow.db \
  --default-artifact-root ./mlruns \
  --host 0.0.0.0 \
  --port 5000